name: Workflow that will run for minor releases and release candidates, for pull requests and also on a nightly basis.

on:
  push:
    tags:
      - v2.*
    branches:
      - r2.9-arm
  pull_request:
    types: [opened, synchronize, reopened]
  schedule:
    - cron: "30 8 * * *"

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Execute a bash command
      run: |
          ci_build.sh cpu.arm64 bash rel/ubuntu/cpu_arm64_py39_pip.sh 
      with:
          path:
              tensorflow/tools/ci_build/

  test:
    runs-on: self-hosted

    steps:
    - name: Execute a bash command
      run: echo "Run Test Scripts Here!"
