name: Workflow that will run for minor releases and release candidates, for pull requests and also on a nightly basis.

on:
  push:
    tags:
      - v2.*
  pull_request:
    types: [opened, synchronize, reopened]
  schedule:
    - cron: "30 8 * * *"

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Execute a bash command
      run: echo "Run Build Script Here!"

  test:
    runs-on: self-hosted

    steps:
    - name: Execute a bash command
      run: echo "Run Test Scripts Here!"
